application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      milo-fg:
        license: Apache-2.0
        actions:
          promote-worker:
            function: actions/promote/worker.js
            web: 'yes'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
